import type { Metadata } from "next"
import Footer  from '@/components/kit/footer'
import { Nav } from '@/components/kit/nav'
import "./globals.css"

export const metadata: Metadata = {
  title: "Mehl",
  description: "Generated by create next app",
  icons: "/window.svg",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
